# Generated by Django 6.0.2 on 2026-07-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_options_alter_organization_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
