# Generated by Django 6.0.2 on 2026-07-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_address_customuser_contact_number"),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("name", "organization")},
        ),
    ]
